#!/bin/bash

source script.conf
source script.utils

SCRIPT_SOURCE=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
pushd $SCRIPT_SOURCE

line_nr=0

while read -r line || [[ -n "$line" ]]
do
  ((++line_nr))

  # skip comments and empty lines
  is_comment_or_empty $line && continue
  info $line

done < "$BUILD_CONF"

popd