version: '3.6'
services:
  db:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: ${PROJECT_NAME}_db
    volumes:
      - './data/mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_DATABASE=${PROJECT_NAME:-wordpress}
      - MYSQL_USER=${DB_USER:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
    restart: always

  wordpress:
    image: wordpress:${WP_VERSION:-latest}
    container_name: ${PROJECT_NAME:-wordpress}
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/php.ini
      - ./data/wordpress:/var/www/html
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/themes:/var/www/html/wp-content/themes
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_TABLE_PREFIX=${WP_TABLE_PREFIX:-wp_}
      - WORDPRESS_DB_NAME=${PROJECT_NAME:-wordpress}
      - WORDPRESS_DB_USER=${DB_USER:-root}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD:-password}
      - WORDPRESS_DEBUG=1
    depends_on:
      - db
    restart: always
    ports:
      - 127.0.0.3:80:80
