#!/bin/bash

CONFIG="repositories.conf"

SCRIPT_SOURCE=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

SRC_DIR="src"

function colorize {
  local RESET='\033[0m'
  local COL=$1
  shift
  printf "${COL}$@${RESET}\n"
}

function warn {
  colorize '\033[0;33m' "$@"
}

function info {
  colorize '\033[0;36m' "$@"
}

function pushd {
  command pushd "$@" > /dev/null
}

function popd {
  command popd "$@" > /dev/null
}

pushd $SCRIPT_SOURCE

line_nr=0

while read -r line || [[ -n "$line" ]]
do
  ((++line_nr))
  info $line

  # skip comments and empty lines
  [[ $line =~ ^#.* ]] || [[ -z $line ]] && continue

  name=${line%%:*}
  repository=${line#*:}
  folder="${SRC_DIR}/${name}"

  # wrong format
  [[ $line != *":"* ]] || [[ -z $name ]] || [[ -z $repository ]] \
    && warn "ERROR: Wrong format!" \
    && echo "Ignoring line ${line_nr}: ${line}" \
    && echo "See README for documentation." \
    && continue

  # check if folder exists, if not clone
  [[ ! -d $folder ]] && git clone $repository $folder

  [[ ! -d $folder ]] \
    && warn "ERROR: Source folder '${folder}' does not exist." \
    && echo "There might have been an error cloning the repository '${repository}'" \
    && echo "Ignoring line ${line_nr}: ${line}" \
    && continue

  [[ $# -eq 0 ]] && continue

  pushd $folder

  info "${name}: git ${@}"
  git "$@"

  popd

done < "$CONFIG"

popd